### ISSUE TITLE
GodsEye causing lag on the server

### ISSUE THREAD

**Issue by harry2512tea** [Nort721/GodsEye-Issues#61] opened 2019-11-01 17:49 UTC
A bug report/issue report should contain:

1) Server Version+Fork: 1.14.4
2) ProtocolLib version 4.4.0
3) https://pastebin.com/6nHdRhG8
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.
![2019-11-01_16 59 25](https://user-images.githubusercontent.com/25117775/68042027-caa5cb80-fcc9-11e9-85b3-84edbed46a3b.png)

5) when players who aren't administrators load into the server, the anti-cheat kicks off and spams chat (when using verbose) with every player and a lot of anti-cheat checks. kicking the primary target of the anti-cheat just causes it to pick on another player.

**Comment by Nort721** [comment] 2019-11-01 17:52
as I see in the picture looks like only the AimAssist and Movement checks are falsing, is there more checks that are false, if there are list them please

**Comment by harry2512tea** [comment] 2019-11-01 17:53
its the movement check, aim assist and regen checks. (I exaggerated the extent sorry, fixed it now)

**Comment by Nort721** [comment] 2019-11-01 17:55
ok, and are you sure that GodsEye is kicking them? do you get the kick messages in chat? also, can you send here a Pastebin of all of your recent console logs please?

**Comment by harry2512tea** [comment] 2019-11-01 18:03
no godseye isn't kicking anyone, we kicked the player to see if it would stop the spam

**Comment by Nort721** [comment] 2019-11-01 18:05
oh, so GodsEye did not kick players, btw about the high ping in tab you said players hade did their actions got delayed?

**Comment by harry2512tea** [comment] 2019-11-01 18:05
that got fixed by our hosting company, the godseye issue remained after it was fixed

**Comment by Nort721** [comment] 2019-11-01 18:09
> that got fixed by our hosting company, the godseye issue remained after it was fixed

so the player's actions are delayed i.e do they feel lag when the ping in the tab is on one bar?

**Comment by harry2512tea** [comment] 2019-11-01 18:11
yes, they do an action, and after a long delay the action actually happens on the server.

**Comment by harry2512tea** [comment] 2019-11-01 18:14
disabling those checks has stopped the chat from getting spammed when verbose is enabled, but console still gets spammed with GodsEye tasks generating exceptions

**Comment by Nort721** [comment] 2019-11-01 18:16
> yes, they do an action, and after a long delay the action actually happens on the server.

Hmm, it's hard to know if it's related to GodsEye but I will try checking it out, also I am working on more optimizations for next update, generate some timings of like 1 - 3 hours when you can and send them here, they would really help for me to find the cause of the lag



> disabling those checks has stopped the chat from getting spammed when verbose is enabled, but console still gets spammed with GodsEye tasks generating exceptions

send here some Pastebin of the whole errors, please

**Comment by harry2512tea** [comment] 2019-11-01 18:22
https://pastebin.com/8PrW5Vc5

**Comment by Nort721** [comment] 2019-11-01 18:23
ok so I've just found the cause of all of the problems that you are having

**Comment by Nort721** [comment] 2019-11-01 18:24
you are not using the correct version of ProtocolLib, please use this version http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/artifact/build/libs/ProtocolLib.jar restart the server when you update it

**Comment by Nort721** [comment] 2019-11-01 18:31
I will be closing this issue now since that you hade the incorrect version of ProtocolLib probably explains  all of the issues you hade, please message me on the discord server if you are having this issues again after updating ProtocolLib, if you will have them again I will reopen this issue

**Closed by Nort721** 2019-11-01 18:31 UTC
