### ISSUE TITLE
Godseye not working good anymore with this error!

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#206] opened 2020-06-05 18:30 UTC
A bug report/issue report should contain:

1) 33B
2) FoxSpigot 1.8.8
3) 4.4.0
4) https://pastebin.com/9WQ7qv2X + https://prnt.sc/sujipi
5) https://pastebin.com/9WQ7qv2X + https://prnt.sc/sujipi
6) So when the person is like getting detected 1 time for killaura or something like that it gets kicked for some weird message and this error pops up in the console..... It is not working good anymore

**Comment by Nort721** [comment] 2020-06-06 12:25
Unfortunatly I cant do much about it rn, you are the only one having this issue so its probably something with your config or plugins, try removing plugins until the error is gone or resetting your config

**Comment by jackstaak** [comment] 2020-06-06 12:27
Well that is really sad to hear because I am 100% sure it is not one of my plugins. I reinstalled godseye already and it is still giving the same errors....

**Comment by Nort721** [comment] 2020-06-06 12:27
Maybe its related to FoxSpigot, try replacing it with paper or normal spigot and see if it happens

**Comment by jackstaak** [comment] 2020-06-06 12:28
I never had this problem and I am using foxspigot for quite some time now and foxspigot had like 0 iss ues.

**Comment by Nort721** [comment] 2020-06-06 13:02
Well as I said in your other issue, this error have started happening only to you recently, so its probably something in your server causing it

**Comment by jackstaak** [comment] 2020-06-06 13:02
I am gonna use paperspigot rn if it still happens you gotta investigate more then

**Comment by jackstaak** [comment] 2020-06-06 13:11
https://prnt.sc/suwkd3 + getting this kick when I get kicked from godseye! it is defintely not working good even with paperspigot!!!!

**Comment by Nort721** [comment] 2020-06-13 17:27
We found later that the error was caused by your server for some reason, thats why I closing this issue, if it still happens and you can't find why, please comment on this issue, and I will reopen it

**Closed by Nort721** 2020-06-13 17:27 UTC
Labels: error
